services:
  front:
    build:
      context: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - ".env"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command:
      #- poetry run uvicorn app.app:app --host 0.0.0.0 --reload
      - /bin/sh -c "while sleep 1000; do :; done"
